### ISSUE TITLE
Enforce initiative order on a combat action

### ISSUE THREAD

**Issue by Cadair** [SolarDrew/skill-rpgchar#25]
I.e. you shouldn't be able to do an attack until it's your turn

**Comment by SolarDrew** [comment]
By extension, you shouldn't be able to take _any_ action not on your turn. I was considering having a `@match_active_player` decorator or similar, to only trigger skills if the right person is speaking.

**Comment by SolarDrew** [comment]
Related: #29

**Comment by SolarDrew** [comment]
Enforcing this will have a practical drawback of also disallowing reactions, so that will need to be worked around.
